# Generated by Django 4.1.4 on 2022-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On Loan'), ('a', 'Available'), ('m', 'Maintenance'), ('r', 'Reserved')], default='m', max_length=1),
        ),
    ]
